//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagmentSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADAY_CARI_HESAPLAR
    {
        public System.Guid adaycr_Guid { get; set; }
        public short adaycr_DBCno { get; set; }
        public Nullable<int> adaycr_SpecRECno { get; set; }
        public Nullable<bool> adaycr_iptal { get; set; }
        public Nullable<short> adaycr_fileid { get; set; }
        public Nullable<bool> adaycr_hidden { get; set; }
        public Nullable<bool> adaycr_kilitli { get; set; }
        public Nullable<bool> adaycr_degisti { get; set; }
        public Nullable<int> adaycr_checksum { get; set; }
        public Nullable<short> adaycr_create_user { get; set; }
        public System.DateTime adaycr_create_date { get; set; }
        public Nullable<short> adaycr_lastup_user { get; set; }
        public Nullable<System.DateTime> adaycr_lastup_date { get; set; }
        public string adaycr_special1 { get; set; }
        public string adaycr_special2 { get; set; }
        public string adaycr_special3 { get; set; }
        public string adaycr_kod { get; set; }
        public string adaycr_unvan1 { get; set; }
        public string adaycr_unvan2 { get; set; }
        public string adaycr_sektor_kodu { get; set; }
        public string adaycr_bolge_kodu { get; set; }
        public string adaycr_grup_kodu { get; set; }
        public string adaycr_temsilci_kodu { get; set; }
        public string adaycr_wwwadresi { get; set; }
        public string adaycr_EMail { get; set; }
        public string adaycr_adr1_cadde { get; set; }
        public string adaycr_adr1_mahalle { get; set; }
        public string adaycr_adr1_sokak { get; set; }
        public string adaycr_adr1_Semt { get; set; }
        public string adaycr_adr1_Apt_No { get; set; }
        public string adaycr_adr1_Daire_No { get; set; }
        public string adaycr_adr1_posta_kodu { get; set; }
        public string adaycr_adr1_ilce { get; set; }
        public string adaycr_adr1_il { get; set; }
        public string adaycr_adr1_ulke { get; set; }
        public string adaycr_adr1_adres_kodu { get; set; }
        public string adaycr_adr1_tel_ulke_kodu { get; set; }
        public string adaycr_adr1_tel_bolge_kodu { get; set; }
        public string adaycr_adr1_tel_no1 { get; set; }
        public string adaycr_adr2_cadde { get; set; }
        public string adaycr_adr2_mahalle { get; set; }
        public string adaycr_adr2_sokak { get; set; }
        public string adaycr_adr2_Semt { get; set; }
        public string adaycr_adr2_Apt_No { get; set; }
        public string adaycr_adr2_Daire_No { get; set; }
        public string adaycr_adr2_posta_kodu { get; set; }
        public string adaycr_adr2_ilce { get; set; }
        public string adaycr_adr2_il { get; set; }
        public string adaycr_adr2_ulke { get; set; }
        public string adaycr_adr2_adres_kodu { get; set; }
        public string adaycr_adr2_tel_ulke_kodu { get; set; }
        public string adaycr_adr2_tel_bolge_kodu { get; set; }
        public string adaycr_adr2_tel_no1 { get; set; }
        public string adaycr_yetkili1_isim { get; set; }
        public string adaycr_yetkili1_dahili_telno { get; set; }
        public string adaycr_yetkili1_email_adres { get; set; }
        public string adaycr_yetkili1_cep_telno { get; set; }
        public string adaycr_yetkili2_isim { get; set; }
        public string adaycr_yetkili2_dahili_telno { get; set; }
        public string adaycr_yetkili2_email_adres { get; set; }
        public string adaycr_yetkili2_cep_telno { get; set; }
        public string adaycr_yetkili3_isim { get; set; }
        public string adaycr_yetkili3_dahili_telno { get; set; }
        public string adaycr_yetkili3_email_adres { get; set; }
        public string adaycr_yetkili3_cep_telno { get; set; }
        public string adaycr_yetkili4_isim { get; set; }
        public string adaycr_yetkili4_dahili_telno { get; set; }
        public string adaycr_yetkili4_email_adres { get; set; }
        public string adaycr_yetkili4_cep_telno { get; set; }
        public string adaycr_yetkili5_isim { get; set; }
        public string adaycr_yetkili5_dahili_telno { get; set; }
        public string adaycr_yetkili5_email_adres { get; set; }
        public string adaycr_yetkili5_cep_telno { get; set; }
    }
}
