//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagmentSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICILAR
    {
        public System.Guid User_Guid { get; set; }
        public short User_DBCno { get; set; }
        public Nullable<int> User_SpecRECno { get; set; }
        public Nullable<bool> User_iptal { get; set; }
        public Nullable<short> User_fileid { get; set; }
        public Nullable<bool> User_hidden { get; set; }
        public Nullable<bool> User_kilitli { get; set; }
        public Nullable<bool> User_degisti { get; set; }
        public Nullable<int> User_checksum { get; set; }
        public Nullable<short> User_create_user { get; set; }
        public System.DateTime User_create_date { get; set; }
        public Nullable<short> User_lastup_user { get; set; }
        public Nullable<System.DateTime> User_lastup_date { get; set; }
        public string User_special1 { get; set; }
        public string User_special2 { get; set; }
        public string User_special3 { get; set; }
        public Nullable<int> User_no { get; set; }
        public string User_name { get; set; }
        public string User_pw { get; set; }
        public string User_LongName { get; set; }
        public string User_LoginName { get; set; }
        public string User_EMail { get; set; }
        public Nullable<bool> User_InSystem { get; set; }
        public Nullable<byte> User_ProgNo { get; set; }
        public string User_Modules { get; set; }
        public Nullable<int> User_random { get; set; }
        public string User_DBase { get; set; }
        public Nullable<byte> User_SifreTipi { get; set; }
        public Nullable<System.DateTime> User_SifreDegisim_date { get; set; }
        public Nullable<bool> User_pasif { get; set; }
        public string User_FirstIP { get; set; }
        public string User_LastIP { get; set; }
        public string User_PrevPW1 { get; set; }
        public string User_PrevPW2 { get; set; }
        public string User_PrevPW3 { get; set; }
        public string User_PrevPW4 { get; set; }
        public string User_PrevPW5 { get; set; }
        public string User_DomainAndUserName { get; set; }
        public string User_DefaultDBKod { get; set; }
        public string User_eMikroMail { get; set; }
        public string User_eMikroSifre { get; set; }
        public string User_KEPHesap { get; set; }
        public string User_KEPCepTelefonu { get; set; }
        public string User_KEPSifre { get; set; }
        public string User_KEPTcNo { get; set; }
        public Nullable<byte> User_Eimza_tipi { get; set; }
        public string User_Eimza_surucusu { get; set; }
        public string User_Eimza_sifre { get; set; }
        public Nullable<bool> User_SRVfl { get; set; }
        public Nullable<bool> User_outlook_takvim_senk_fl { get; set; }
        public Nullable<bool> User_gmail_takvim_senk_fl { get; set; }
        public string User_gmail_takvim_ical_adres { get; set; }
        public string User_pc_name { get; set; }
        public Nullable<short> User_outlook_takvim_senk_dk { get; set; }
        public Nullable<short> User_gmail_takvim_senk_dk { get; set; }
        public string User_kbs_sifre { get; set; }
        public string User_LVKN { get; set; }
        public Nullable<System.Guid> User_idm_user_invitations_id { get; set; }
        public Nullable<System.Guid> User_idm_user_id { get; set; }
        public Nullable<int> User_idm_user_invitations_int_id { get; set; }
        public string User_idm_user_email { get; set; }
        public Nullable<byte> User_Hatali_giris_sayisi { get; set; }
        public string User_Ceptel { get; set; }
    }
}
