//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagmentSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICILAR_USER
    {
        public System.Guid Record_uid { get; set; }
        public Nullable<bool> Numune_Giris { get; set; }
        public Nullable<bool> Numune_Duzeltme { get; set; }
        public Nullable<bool> Numune_Silme { get; set; }
        public Nullable<bool> Numune_Sonuc_Giris { get; set; }
    }
}
