//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagmentSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUMUNE_HAREKETLERI
    {
        public int nmnh_id { get; set; }
        public System.DateTime nmnh_createdate { get; set; }
        public System.DateTime nmnh_lastupdate { get; set; }
        public Nullable<int> nmnh_nmnid { get; set; }
        public string nmnh_nmnkod { get; set; }
        public string nmnh_kod { get; set; }
        public string nmnh_sonucsirano { get; set; }
        public System.DateTime nmnh_bitistarih { get; set; }
        public System.DateTime nmnh_alistarih { get; set; }
        public Nullable<double> nmnh_maliyetEuo { get; set; }
        public Nullable<double> nmnh_maliyetYonetim { get; set; }
        public Nullable<double> nmnh_isikhas { get; set; }
        public Nullable<double> nmnh_isidayanim { get; set; }
        public Nullable<double> nmnh_rroran { get; set; }
        public Nullable<byte> nmnh_gida { get; set; }
        public byte nmnh_labonay { get; set; }
        public string nmnh_aciklama { get; set; }
    }
}
