//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagmentSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_ALT_GRUPLARI
    {
        public System.Guid sta_Guid { get; set; }
        public short sta_DBCno { get; set; }
        public Nullable<int> sta_SpecRECno { get; set; }
        public Nullable<bool> sta_iptal { get; set; }
        public Nullable<short> sta_fileid { get; set; }
        public Nullable<bool> sta_hidden { get; set; }
        public Nullable<bool> sta_kilitli { get; set; }
        public Nullable<bool> sta_degisti { get; set; }
        public Nullable<int> sta_checksum { get; set; }
        public Nullable<short> sta_create_user { get; set; }
        public System.DateTime sta_create_date { get; set; }
        public Nullable<short> sta_lastup_user { get; set; }
        public Nullable<System.DateTime> sta_lastup_date { get; set; }
        public string sta_special1 { get; set; }
        public string sta_special2 { get; set; }
        public string sta_special3 { get; set; }
        public string sta_kod { get; set; }
        public string sta_isim { get; set; }
        public string sta_ana_grup_kod { get; set; }
    }
}
