//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagmentSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLab
    {
        public int id { get; set; }
        public Nullable<System.DateTime> lab_bitis_tarih { get; set; }
        public string lab_aciklama { get; set; }
        public Nullable<int> lab_maliyet1 { get; set; }
        public Nullable<int> lab_isik_hasligi { get; set; }
        public Nullable<int> lab_isi_dayanimi { get; set; }
        public Nullable<bool> lab_gida { get; set; }
        public Nullable<int> lab_reach_rohs_oran { get; set; }
        public Nullable<int> lab_maliyet2 { get; set; }
        public Nullable<bool> lab_sonuc { get; set; }
        public Nullable<bool> lab_musteri_onay { get; set; }
    }
}
