//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagmentSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNumuneler
    {
        public int id { get; set; }
        public string nmn_kod { get; set; }
        public Nullable<System.DateTime> nmn_tarih { get; set; }
        public string nmn_cari_seviye { get; set; }
        public string nmn_aciliyet { get; set; }
        public string nmn_aday_cari { get; set; }
        public string nmn_aday_carikonum { get; set; }
        public Nullable<int> nmn_sip_miktar { get; set; }
        public Nullable<int> nmn_deneme_miktar { get; set; }
        public Nullable<int> nmn_hdf_fiyat { get; set; }
        public string nmn_fiyat_cins { get; set; }
        public string nmn_mus_yetkili { get; set; }
        public string nmn_is_merkezi { get; set; }
        public string nmn_rkpcari_ad { get; set; }
        public string nmn_rkpcari_urunkod { get; set; }
        public string nmn_tur { get; set; }
        public string nmn_uretilecek_urun { get; set; }
        public string nmn_hammadde { get; set; }
        public Nullable<double> nmn_mfi { get; set; }
        public Nullable<int> nmn_oran { get; set; }
        public string nmn_gida { get; set; }
        public string nmn_reach_rohs { get; set; }
        public Nullable<System.DateTime> nmn_termintarih { get; set; }
        public string nmn_aciklama { get; set; }
    }
}
