//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagmentSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        public System.Guid uru_Guid { get; set; }
        public short uru_DBCno { get; set; }
        public Nullable<int> uru_SpecRECno { get; set; }
        public Nullable<bool> uru_iptal { get; set; }
        public Nullable<short> uru_fileid { get; set; }
        public Nullable<bool> uru_hidden { get; set; }
        public Nullable<bool> uru_kilitli { get; set; }
        public Nullable<bool> uru_degisti { get; set; }
        public Nullable<int> uru_checksum { get; set; }
        public Nullable<short> uru_create_user { get; set; }
        public System.DateTime uru_create_date { get; set; }
        public Nullable<short> uru_lastup_user { get; set; }
        public Nullable<System.DateTime> uru_lastup_date { get; set; }
        public string uru_special1 { get; set; }
        public string uru_special2 { get; set; }
        public string uru_special3 { get; set; }
        public string uru_stok_kod { get; set; }
        public Nullable<double> uru_gider1 { get; set; }
        public Nullable<double> uru_gider2 { get; set; }
        public Nullable<double> uru_gider3 { get; set; }
        public Nullable<double> uru_gider4 { get; set; }
        public Nullable<double> uru_gider5 { get; set; }
        public Nullable<byte> uru_tip { get; set; }
        public Nullable<double> uru_max_fire_yuz { get; set; }
        public Nullable<double> uru_min_fire_yuz { get; set; }
        public Nullable<double> uru_fasonmaliyet { get; set; }
        public Nullable<double> uru_partimiktari { get; set; }
        public string uru_isemriID { get; set; }
        public Nullable<double> uru_uretimortakcarpani { get; set; }
        public Nullable<byte> uru_uretimsekli { get; set; }
        public string uru_formdosyaadi { get; set; }
        public string uru_excdosyaadi { get; set; }
        public Nullable<int> uru_ongorulendepo { get; set; }
        public Nullable<double> uru_gider6 { get; set; }
        public Nullable<double> uru_gider7 { get; set; }
        public Nullable<double> uru_gider8 { get; set; }
        public Nullable<double> uru_gider9 { get; set; }
        public Nullable<double> uru_gider10 { get; set; }
        public Nullable<byte> uru_ozel_tipi { get; set; }
        public Nullable<double> uru_sabitmlyt_anauruncarpan { get; set; }
        public string uru_masterrecete { get; set; }
        public string uru_SorumlulukMerkezi { get; set; }
        public string uru_varsayilanismerkezi { get; set; }
        public string uru_Muhgrup_kodu { get; set; }
        public string uru_masterkalip_kodu { get; set; }
        public string uru_recete_ismi1 { get; set; }
        public string uru_recete_ismi2 { get; set; }
        public string uru_recete_ismi3 { get; set; }
        public string uru_recete_ismi4 { get; set; }
        public string uru_recete_ismi5 { get; set; }
        public string uru_varsayilan_recete_tanim_kodu { get; set; }
        public Nullable<byte> uru_varsayilan_recete_cins { get; set; }
    }
}
